[build-system]
requires = [
  "setuptools >= 45.0.0",  # required by pyproject+setuptools_scm integration
  "setuptools_scm[toml] >= 7.0.0",  # required for "no-local-version" scheme
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
