Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine310"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider :libvirt do |l|
    l.nic_model_type = "e1000"
    l.driver = "qemu"
    l.cpu_mode = 'custom'
    l.cpu_model = 'core2duo'
  end
end
