Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine310"
  config.vm.provider :libvirt do |l|
    l.driver = "qemu"
    l.cpu_mode = 'custom'
    l.cpu_model = 'core2duo'
  end
  config.vm.provision :shell, inline: "sudo apk add --no-progress --update python3 rsync"
  config.ssh.insert_key = false
end
